Sooryen/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sooryen.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Login()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
    }
}

Sooryen/Controllers/NoteController.cs
using Sooryen.Business.Interface;
using Sooryen.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Sooryen.Controllers
{
    public class NoteController : Controller
    {

        public INoteManager NoteManger { get; }

        public NoteController(INoteManager noteManger)
        {
            NoteManger = noteManger;
        }


        // GET: Note
        public ActionResult Notes()
        {
            return View();
        }

        public async Task<JsonResult> GetAllNotes()
        {
            return Json(await NoteManger.GetNotes(), JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> AddNote(NoteModel item)
        {
            item.Id= await NoteManger.Add(item);
            return Json(item, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> EditNote(int id, NoteModel Note)
        {
            Note.Id = id;
            var result = await NoteManger.Update(Note);
            if (result)
            {
                return Json(await NoteManger.GetNotes(), JsonRequestBehavior.AllowGet);
            }

            return Json(null);
        }

        public async Task<JsonResult> DeleteNote(int id)
        {

            return Json(new { Status = await NoteManger.Delete(id) }, JsonRequestBehavior.AllowGet);

        }
    }
}

Sooryen/Controllers/UserController.cs
using Sooryen.Business.Interface;
using Sooryen.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Sooryen.Controllers
{
    public class UserController : Controller
    {


        public IUserManager UserManager { get; }

        public UserController(IUserManager userManager)
        {
            UserManager = userManager;
        }


        [HttpPost]

        public async Task<ActionResult> UserLogin(UserModel user)
        {
            var userDetail = await UserManager.UserLogin(user);
            return View(userDetail);
        }

    }
}

Sooryen/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Sooryen/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Sooryen/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Sooryen/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<h4>Use a local account to log in.</h4>
<hr />
<div class="form-group">

    <div class="col-md-12">
       User Name

    </div>
</div>
<div class="form-group">
   
    <div class="col-md-12">
        <input type="text" id="userName" />

    </div>
</div>
<div class="form-group">

    <div class="col-md-12">
        Password
    </div>
</div>
<div class="form-group">
    
    <div class="col-md-12">
        <input type="password" id="Password" />
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-12">
        <input type="submit" value="Log in" id="btnLogin" class="btn btn-default" onclick="user.Login()" />
    </div>
</div>

<script src="~/Scripts/User.js"></script>

Sooryen/Views/Note/Notes.cshtml
@{
    ViewBag.Title = "Notes";
}

@section scripts {
<script src="~/Scripts/knockout-3.5.0.js"></script>
<script src="~/Scripts/knockout-3.5.0.debug.js"></script>
<script src="~/Scripts/Notes.js"></script>
}


<h2>Notes</h2>

<table class="table">
    <tr>
        <td>
            <table class="table">
                <tbody data-bind="foreach: Notes">
                    <tr>
                        <td data-bind="text: Title"></td>
                        <td data-bind="text: Body"></td>
                        <td>
                            <button data-bind="click: $root.delete">Delete</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </td>
        <td>
            <table class="table">
                <tbody>
                    <tr>
                        <td align="right"><button data-bind="click: $root.create">Add Note</button></td>
                    </tr>
                    <tr>
                        <td>
                            <div data-bind="ifnot: Note()">
                                <div>
                                    <label for="Title">Title</label>
                                    <input data-bind="value: $root.Title" type="text" title="Title" />
                                </div>

                                <div>
                                    <label for="Body">Body</label>
                                    <input data-bind="value: $root.Body" type="text"  title="Body" height="100" />
                                </div>
                                <br />
                                <div>
                                    <button data-bind="click: $root.create">Save</button>
                                    <button data-bind="click: $root.reset">Reset</button>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </td>
    </tr>
</table>

Sooryen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Login", "Login", "Home")</li>

                    <li>@Html.ActionLink("Notes", "Notes", "Note")</li>

                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

<script src="~/Scripts/DataService.js"></script>
    <script src="~/Scripts/User.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Sooryen/Views/User/UserLogin.cshtml
@{
    ViewBag.Title = "UserLogin";
}

<h2>UserLogin</h2>